### ISSUE TITLE
The mod could not work on 1.20.1 

### ISSUE THREAD

**Issue by crackun24** [OKTW-Network/FabricProxy-Lite#58]
This is the error msg when player join the game :Internal Exception: java.lang.NoSuchMethodError: het.minecraft.class_3218
Fabric api version: 0.83.1

**Comment by james58899** [comment]
What version are you using? And attach the full log.

**Comment by crackun24** [comment]
I have solved it by updating the velocity to the latest version,Sorry to disturb you.
